name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'

jobs:
  Lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Pnpm Action
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1
      - name: Install modules
        run: pnpm install
      - name: Run Lint
        run: cd packages/moc-ui && pnpm run lint
        
  UnitTest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Pnpm Action
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1

      - name: Install modules
        run: pnpm install

      - name: Run Test
        run:  cd packages/moc-ui && pnpm run test:run

  PreBuild:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Git Source
        uses: actions/checkout@v2

      - name: Pnpm Action
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 7.2.1

      - name: Install modules
        run: pnpm install
        
      - name: Run Lint
        run: cd packages/moc-ui  && pnpm run build
